include = [
    "api/**/*.py",
    "common/**/*.py",
    "evaluator/**/*.py",
    "kelvin/**/*.py",
    "survey/**/*.py",
    "web/**/*.py"
]
exclude = [
    "**/migrations/**"
]

line-length = 100
indent-width = 4

target-version = "py312"
