# Generated by Django 3.0b1 on 2019-11-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_group_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='moss_url',
            field=models.URLField(null=True),
        ),
    ]
