# Generated by Django 3.0b1 on 2019-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_assignedtask_moss_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='moss_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
