# Generated by Django 3.0.1 on 2020-01-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20191117_2054'),
    ]

    operations = [
    ]
