# Generated by Django 3.0.3 on 2020-03-13 18:45

from django.db import migrations, models
import django.db.models.deletion

def create_upr(apps, schema_editor):
    Subject = apps.get_model('common', 'Subject')
    Semester = apps.get_model('common', 'Semester')

    s = Subject()
    s.name = 'Úvod do programování'
    s.abbr = 'UPR'
    s.save()

    s = Semester()
    s.begin = '2019-09-16'
    s.end = '2020-02-09'
    s.year = 2019
    s.winter = True
    s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_api_token_as_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('year', models.IntegerField()),
                ('winter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.RunPython(create_upr),
        migrations.RemoveField(
            model_name='class',
            name='winter',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year',
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Subject'),
            preserve_default=False,
        ),
    ]
