# Generated by Django 3.0.3 on 2020-03-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_split_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='source',
        ),
    ]
