# Generated by Django 3.0.3 on 2020-03-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='moss_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=60, verbose_name='Directory'),
        ),
    ]
