# Generated by Django 3.0.3 on 2020-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200315_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='assigned_points',
            field=models.IntegerField(null=True),
        ),
    ]
