# Generated by Django 3.0.3 on 2020-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_submit_assigned_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='assigned_points',
            field=models.FloatField(null=True),
        ),
    ]
