# Generated by Django 3.0.3 on 2020-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_assigned_points_as_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='announce',
            field=models.BooleanField(default=False),
        ),
    ]
