# Generated by Django 3.0.3 on 2020-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_task_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='jobid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
