# Generated by Django 3.0.7 on 2020-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_submit_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=60, unique=True, verbose_name='Directory'),
        ),
    ]
