# Generated by Django 3.0.7 on 2020-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_task_unique_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
