# Generated by Django 3.1.14 on 2023-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_pgsql_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plagiarism_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
