# Generated by Django 3.1.14 on 2023-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_task_plagiarism_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='ip_address',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
