# Generated by Django 4.2.16 on 2025-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_remove_submit_ip_address_hash_submit_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('homework', 'Homework'), ('exam', 'Exam'), ('project', 'Project'), ('laboratory', 'Laboratory'), ('other', 'Other')], default=None, max_length=10, null=True),
        ),
    ]
