# Generated by Django 4.2.16 on 2025-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='plagiarism_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
