# Generated by Django 4.2.16 on 2025-03-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0025_alter_task_plagiarism_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('submit', 'Submit')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP address')),
                ('metadata', models.JSONField(null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user event',
                'db_table': 'common_user_event',
            },
        ),
    ]
