# Generated by Django 4.2.16 on 2025-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_usereventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventmodel',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('submit', 'Submit'), ('task-view', 'Task displayed')], max_length=10),
        ),
    ]
