# Generated by Django 4.2.16 on 2025-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_usereventmodel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='hard_deadline',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
