# Generated by Django 4.2.16 on 2025-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_assignedtask_hard_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usereventmodel',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('submit', 'Submit'), ('task-view', 'Task displayed'), ('mark-submit', 'Submit marked as final')], max_length=15),
        ),
    ]
