# Generated by Django 4.2.16 on 2025-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_submit_is_final_alter_usereventmodel_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomIpRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ip_range_start', models.GenericIPAddressField()),
                ('ip_range_end', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='allowed_classrooms',
            field=models.ManyToManyField(related_name='assignments', to='common.classroomiprange'),
        ),
    ]
