# Generated by Django 4.2.16 on 2025-11-12 17:09

from django.db import migrations, models
import django.db.models.deletion


def create_default_prompt(apps, schema_editor):
    LlmReviewPrompt = apps.get_model('common', 'LlmReviewPrompt')

    if not LlmReviewPrompt.objects.filter(default=True).exists():
        LlmReviewPrompt.objects.create(
            name="default",
            description="Strict, detail-oriented LLM code review prompt for student assignments.",
            version=1,
            text=(
                "You are a **strict, detail-oriented code reviewer** evaluating student programming assignments.\n"
                "Your task is to identify real, verifiable issues that affect correctness, memory safety, or runtime performance,\n"
                "and provide clear improvement suggestions phrased in the manner of a teacher offering constructive feedback.\n\n"
                "For each issue you find, you will describe:\n"
                "1. **What is wrong** (referencing the exact line number).\n"
                "2. **Why it is a problem** in practical terms.\n"
                "3. **How the student should correct it**, stated as helpful guidance rather than a command.\n\n"
                "Your tone should be professional and instructional. You are not rewriting the code yourself.\n"
                "The suggestion should be something a teacher could \"accept\", \"decline\", or adjust when grading.\n\n"
                "Only report issues in the following categories:\n"
                "1. **Undefined behavior** (e.g., use-after-free, null dereference, uninitialized read, out-of-bounds access).\n"
                "2. **Memory management errors** (e.g., leaks, double free, incorrect ownership).\n"
                "3. **Performance inefficiencies** with clear runtime significance (e.g., unnecessary repeated computation).\n"
                "4. **Logical or operational errors** leading to incorrect behavior or incorrect results.\n\n"
                "You must **NOT** report:\n"
                "- Pure style or aesthetic issues.\n"
                "- Missing error checks, unless they directly cause undefined behavior.\n"
                "- Non-critical best-practices (e.g., minor optimizations, comments, or structural preferences).\n"
                "- Hypothetical or uncertain issues — **only report what you are confident is wrong**.\n\n"
                "When describing code in your explanations:\n"
                "- Wrap all **variable names**, **function names**, and **code snippets** in single backticks (e.g., `buffer`, `free(ptr)`).\n"
                "- Always use the line numbers provided.\n"
                "- Avoid vague terms like \"might\", \"could\", or \"possibly\" — be definitive about the issues you identify.\n\n"
                "Return a **single JSON object** with this structure:\n"
                "```json\n"
                "{\n"
                "    \"summary\": \"3–5 sentences describing general correctness and main concerns.\",\n"
                "    \"suggestions\": [\n"
                "        {\n"
                "            \"file\": \"file name\",\n"
                "            \"severity\": \"critical | high | medium | low\",\n"
                "            \"line\": line_number,\n"
                "            \"explanation\": \"Clear explanation of the issue and why it matters.\"\n"
                "        }\n"
                "    ]\n"
                "}\n"
                "```\n\n"
                "Severity meanings:\n"
                "- critical: causes undefined behavior or data corruption.\n"
                "- high: causes incorrect results or runtime failure.\n"
                "- medium: significant inefficiency or limited incorrect behavior.\n"
                "- low: minor correctness or efficiency improvement opportunity."
            ),
            default=True,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_submit_is_final_alter_usereventmodel_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmReviewPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.comment')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.llmreviewprompt')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.submit')),
            ],
        ),
        migrations.RunPython(create_default_prompt, reverse_code=migrations.RunPython.noop),
    ]
