# Generated by Django 4.2.16 on 2025-11-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_llmreviewprompt_suggestedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('inbus_room_id', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.room'),
        ),
    ]
