# Generated by Django 4.2.16 on 2026-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='email',
            name='sent_at',
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sent_at'], name='sent_at'),
        ),
    ]
