# Generated by Django 4.2.16 on 2026-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_remove_email_sent_at_email_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedcomment',
            old_name='rating',
            new_name='quality_rating',
        ),
        migrations.AddField(
            model_name='suggestedcomment',
            name='relevance_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedcomment',
            name='review_mode',
            field=models.CharField(choices=[('chain_of_thought', 'Chain Of Thought'), ('zero_shot', 'Zero Shot'), ('thinking', 'Thinking')], default='chain_of_thought', max_length=32),
        ),
        migrations.AddField(
            model_name='suggestedcomment',
            name='server',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
