# Generated by Django 4.2.16 on 2026-06-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_remove_email_sent_at_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='allowed_rooms',
            field=models.ManyToManyField(related_name='assignments', to='common.room'),
        ),
        migrations.CreateModel(
            name='RoomIpRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range_start', models.GenericIPAddressField()),
                ('ip_range_end', models.GenericIPAddressField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='common.room')),
            ],
        ),
    ]
