# Generated by Django 4.2.16 on 2026-03-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_classroomiprange_assignedtask_allowed_classrooms'),
        ('common', '0033_remove_email_sent_at_email_sent_at'),
    ]

    operations = [
    ]
