# Generated by Django 4.2.16 on 2026-04-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_rename_rating_suggestedcomment_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='llmreviewprompt',
            unique_together={('name', 'version')},
        ),
        migrations.AddConstraint(
            model_name='llmreviewprompt',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_prompt_name_version'),
        ),
    ]
