# Generated by Django 4.2.16 on 2026-03-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_merge_20260317_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomIpRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range_start', models.GenericIPAddressField()),
                ('ip_range_end', models.GenericIPAddressField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_ranges', to='common.room')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='allowed_classrooms',
        ),
        migrations.DeleteModel(
            name='ClassroomIpRange',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='allowed_rooms',
            field=models.ManyToManyField(related_name='assignments', to='common.roomiprange'),
        ),
    ]
