# Generated by Django 4.2.16 on 2026-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_roomiprange_remove_assignedtask_allowed_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='allowed_rooms',
            field=models.ManyToManyField(related_name='assignments', to='common.room'),
        ),
    ]
