type: object
additionalProperties: false
properties:
  queue:
    type: string
    enum:
      - evaluator
      - cuda
  timeout:
    type: string
  tests:
    type: array
    items:
      additionalProperties: false
      properties:
        name:
          type: string
        title:
          type: string
        exit_code:
          type: integer
        args:
          type: array
          items:
            type: string
  pipeline:
    type: array
    items: 
      allOf:
        - type: "object"
        - required: ["type"]