type: object
additionalProperties: false
properties:
 commands:
  type: array
  items:
    oneOf:
      - type: string
      - type: object
        additionalProperties: false
        properties:
          cmd:
            type: string
            description: "Command to run. Command with prefix of # are hidden from evaluation result."
          display:
            description: "Pattern of created files (jpg, png, videos, ...) that will be shown in evaluation result." 
            type: array
            items:
               type: string
          hide:
           type: boolean
           description: "Hide command and its output from the evaluation result"
          asciinema:
           type: boolean
           description: "Create asciinema video from the program execution"
          timeout:
             oneOf:
               - type: string
               - type: number
