type: object
additionalProperties: false
properties:
 checks:
  type: array
  items:
    type: string
  description: List of used checks from https://clang.llvm.org/extra/clang-tidy/checks/list.html. You may use asterisks and block checks with hyphen.
 files:
  type: array
  items:
    type: string
  description: List of analyzed files,