type: object
additionalProperties: false
properties:
 output:
  description: "Executable name"
  type: string
 flags:
  description: GCC/G++ flags for compilation
  type: string
 ldflags:
  description: "Flags for a linker"
  type: string
 cmakeflags:
  description: Flags of cmake when the makefile is created.
  type: array
  items:
    type: string
