name: Deploy
concurrency: deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'curl --fail --silent --show-error -H"Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" ${{ secrets.DEPLOY_URL }}'
