name: Pyright
on: [pull_request]
jobs:
  pyright:
    name: pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.356
          lib: true
