name: Ruff
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.3
      # Update output format to enable automatic inline annotations.
      - name: Lint Python code
        run: ruff check --output-format=github api common survey web
