name: Test Python
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv==0.4.4
          uv pip sync --system
      # Update output format to enable automatic inline annotations.
      - name: Lint Python code
        run: ruff check --output-format=github
      - name: Check Python formatting
        run: ruff format --check
      # Check that the lockfile does not need to be updated
      # If this fails, run `uv export --format requirements-txt > requirements.txt`.
      - name: Check lockfile
        run: |
          uv lock --locked
          uv export --format requirements-txt > requirements.txt.locked
          diff requirements.txt requirements.txt.locked
